const actionTypes = {
    POST_LOADING: "POST_LOADING",
    FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
    FETCH_POST_FAILED: "FETCH_POST_FAILED",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    //==============================================
    USER_LOADING: "USER_LOADING",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",


    PROCESS_LOGOUT: "PROCESS_LOGOUT",
}
export default actionTypes