const actionTypes = {
    FETCH_POST_START: "FETCH_POST_START",
    FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
    FETCH_POST_FAILED: "FETCH_POST_FAILED",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_FAILED: "CREATE_POST_FAILED",
    //==============================================
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    PROCESS_LOGOUT: "PROCESS_LOGOUT",
}
export default actionTypes